docs(profile): Setting Profile Avatar
verida/documentation pull request #118
Opened 2022-08-12 16:45 UTC by cmcWebCode40

- Added a sample code for setting profile Avatar
closes #117

2022-08-18 21:00 UTC, dmty approved these changes

2022-08-19 02:24 UTC, aurelticot requested changes
- [x] Can you remove the useless title line 53 "Load Profile avatar ..."
- [x] Can you update the title line 57 from "Open my profile" to "Open and modify my profile"
- [x] Apply other inline comments
- [ ] Add a callout below the code block, similar to the info callout [here](https://developers.verida.io/docs/extensions/verifiable-credentials#issuing-a-credential) with something like: "Learn more about Data URL [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs)"

2022-08-19 02:24 UTC, aurelticot commented on docs/client-sdk/profiles.md
> +const avatarUri = 'data:image/png;base64,iVBOR...' // An  encoded as a URI
Can you move this line just above the line `await myProfile.set('avatar', { uri: avatarUri });`?
Can you also add the missing `;` at the end of the line?
Can you modify the comment `// Data URL of base64-encoded image`

2022-08-19 02:24 UTC, aurelticot commented on docs/client-sdk/profiles.md
>  const name = await myProfile.get('name', 'Stevie');
Remove the wrong second parameter in the get method, just: `.get('name)`

2022-08-19 02:24 UTC, aurelticot commented on docs/client-sdk/profiles.md
>  await myProfile.set('name', 'Stevie');
Add a line above with a comment
`// Modify the profile properties`

2022-08-19 02:24 UTC, aurelticot commented on docs/client-sdk/profiles.md
>  const name = await myProfile.get('name', 'Stevie');
Add a line above with a comment
`// Read my profile properties`

2022-08-19 02:24 UTC, aurelticot commented on docs/client-sdk/profiles.md
>  const name = await myProfile.get('name', 'Stevie');
Add a line below with
`console.log(name); // -> Stevie`

2022-08-19 02:24 UTC, aurelticot commented on docs/client-sdk/profiles.md
>  await myProfile.delete('name');
Add a line above with comment
`// Delete a profile property`

2022-08-19 02:24 UTC, aurelticot commented on docs/client-sdk/profiles.md
>  const profileData = await myProfile.getMany();
Add a line below with
`console.log(profileData); // -> { name: 'Stevie', avatar: { uri: 'data:image/png;base64,iVBOR...' }, ...}`

2022-08-23 05:50 UTC, cmcWebCode40 commented on docs/client-sdk/profiles.md
> +const avatarUri = 'data:image/png;base64,iVBOR...' // An  encoded as a URI
fixed

2022-08-23 05:50 UTC, cmcWebCode40 commented on docs/client-sdk/profiles.md
>  await myProfile.set('name', 'Stevie');
fixed

2022-08-23 05:50 UTC, cmcWebCode40 commented on docs/client-sdk/profiles.md
>  const name = await myProfile.get('name', 'Stevie');
fixed

2022-08-23 05:52 UTC, cmcWebCode40 commented on docs/client-sdk/profiles.md
>  const profileData = await myProfile.getMany();
fixed

2022-08-23 05:53 UTC, cmcWebCode40 commented
@aurelticot , i have updated the this PR with the requested changes

2022-08-24 03:27 UTC, aurelticot commented on docs/client-sdk/profiles.md
>  await myProfile.delete('name');
Can you add this comment line?

2022-08-24 03:28 UTC, aurelticot commented on docs/client-sdk/profiles.md
>  const name = await myProfile.get('name', 'Stevie');
Can you add this `console.log` line under the `get('name')`?
```JavaScript
const name = await myProfile.get('name');
console.log(name); // -> Stevie
```

2022-08-24 03:42 UTC, aurelticot requested changes

2022-08-24 03:42 UTC, aurelticot commented on docs/client-sdk/profiles.md
> +
Can you delete this empty line 72?
```JavaScript
const profileData = await myProfile.getMany();
console.log(profileData); // -> ...
```

2022-08-24 03:42 UTC, aurelticot commented on docs/client-sdk/profiles.md
> +
Can you remove this empty line 62 and arrange the whole like this?
```JavaScript
const myProfile = await context.openProfile('public');

// Modify the profile properties
await myProfile.set('name', 'Stevie');
const avatarUri = 'data:image/png;base64,iVBOR...'; //  Data URL of base64-encoded image
await myProfile.set('avatar', { uri: avatarUri, });

```

2022-08-24 03:42 UTC, aurelticot commented on docs/client-sdk/profiles.md
> +// Read my profile properties
Can you change "my" by "the"
```JavaScript
// Read the profile properties
```

2022-08-24 03:42 UTC, aurelticot commented on docs/client-sdk/profiles.md
> +## Open and modify my profile
Can you change this title as follow:
`## Open and modify the current user's profile`

2022-08-24 03:42 UTC, aurelticot commented on docs/client-sdk/profiles.md
>  Open your own profile for the current context:
Can you change this sentence by:
"Open the user's context profile"

2022-08-24 03:42 UTC, aurelticot commented on docs/client-sdk/profiles.md
>  const myProfile = await context.openProfile('public');
Can you change the property name `myProfile` by `userProfile` everywhere in this sample code:
```JavaScript
const userProfile = await context.openProfile('public');

...
```

2022-08-24 05:16 UTC, cmcWebCode40 commented on docs/client-sdk/profiles.md
>  await myProfile.delete('name');
resolved

2022-08-24 05:16 UTC, cmcWebCode40 commented on docs/client-sdk/profiles.md
> +
modified

2022-08-24 05:17 UTC, cmcWebCode40 commented on docs/client-sdk/profiles.md
> +
modified

2022-08-24 05:17 UTC, cmcWebCode40 commented on docs/client-sdk/profiles.md
> +// Read my profile properties
modified

2022-08-24 05:17 UTC, cmcWebCode40 commented on docs/client-sdk/profiles.md
>  Open your own profile for the current context:
modified

2022-08-25 02:27 UTC, aurelticot approved these changes
Ok

2022-08-26 03:53 UTC, merged