docs: Update SSO texts to verida connect
verida/documentation pull request #125
Opened 2022-08-29 04:27 UTC by cmcWebCode40

- Modified all text references of SSO to verida connect
closes #124

2022-08-29 09:46 UTC, aurelticot requested changes
Hey @cmcWebCode40 I made some comments for changes. Most to go back to "single sign-on" as a capability compared to "Verida Connect" as the product name.

Note that there's always an hyphen "-" between "sign" and "on": "single sign-on". There were some typos before, so it's a good opportunity to fix them.

Also, "Verida Connect" being a product name, both words shall always be capitalised (first letter uppercase)

2022-08-29 09:46 UTC, aurelticot commented on docs/single-sign-on-sdk/single-sign-on-sdk.md
> +The Verida Connect SDK is a decentralized verida connect client library and server API that enables seamless QR code authentication via the Verida Vault mobile application.
should keep "single sign-on" as it's the capability, not the product

2022-08-29 09:46 UTC, aurelticot commented on docs/tutorial/SSO.mdx
> +keywords: [Verida, Web3, Developers, Tutorial, Verida Connect]
Should keep "SSO, Single Sign-On" in the list of keywords, maybe add "Verida Connect" in additional.
I'm guessing keywords are used for the search, SEO, ...

2022-08-29 09:46 UTC, aurelticot commented on docs/tutorial/SSO.mdx
> +title: Verida Connect
I think we should keep "Single Sign-On" for the title and description as it is about the capability, not the product. The other tutorials are not called "Verida Identity", "Verida DbStore", ...

2022-08-29 09:46 UTC, aurelticot commented on docs/client-sdk/how-it-works.md
> +Here’s is the basic flow of the Vault verida connect and what is happening behind the scenes.
@cmcWebCode40: you can keep "single sign-on" here as it is about the capability, not the product.

@nick-verida that first part and diagram about the "Client SDK" is weird because it's just about the authentication flow which is ... in the "Verida Connect SDK".
I think we should update the diagram to show a more high level sequence representing authentication, then data, then messages, ... corresponding to the sections of the page below. Not in this ticket though.

2022-08-29 10:01 UTC, cmcWebCode40 commented on docs/client-sdk/how-it-works.md
> +Here’s is the basic flow of the Vault verida connect and what is happening behind the scenes.
Thanks, @aurel for the feedbacks, i will make changes accordingly.

2022-08-29 13:59 UTC, cmcWebCode40 commented on docs/single-sign-on-sdk/_category_.json
> +	"label": "Verida SDK",
I will use "Verida Connect SDK"

2022-08-30 06:17 UTC, aurelticot requested changes
Some additional change requests

2022-08-30 06:17 UTC, aurelticot commented on docs/single-sign-on-sdk/single-sign-on-sdk.md
> +[The Verida Connect Authentication Server](the-sso-authentication-server.md)
Looks like we're going to call this page simply "Authentication Server"

2022-08-30 06:17 UTC, aurelticot commented on docs/tutorial/SSO.mdx
> +keywords: [Verida, Web3, Developers, Tutorial, Single Sign-On,Verida Connect]
Can you add "SSO" as well in the list of keywords?

2022-08-30 06:17 UTC, aurelticot commented on docs/single-sign-on-sdk/_category_.json
> +	"label": "Verida SDK",
I'm not convinced about "Verida Connect SDK" in the sidebar. I think it would be cleaner to say "Connect SDK", like we say "Client SDK" not Verida Client SDK. Even if technically the "Verida Client" is not an actual thing in our glossary

2022-08-30 06:17 UTC, aurelticot commented on docs/tutorial/SSO.mdx
> +title: Verida Connect
I saw you changed back the title, can you also revert the description?

2022-08-30 06:17 UTC, aurelticot commented on docs/extensions/vue-starter-kit.md
> +This component is used to display a logged-in user profile details such as `name`, `did` and `avatar`. If the user is not logged in it will supply a login link and generate the Verida Connect login f
The typos are not fixed in the latest batch changes

2022-08-30 21:50 UTC, cmcWebCode40 commented on docs/demos.md
> +which demonstrates use cases, features and capabilities of the Verida Vault (eg single sign-on, send a credential, request some data) </summary>
@aurelticot  Do you mean using "signing in" instead of "sign on"?

2022-08-30 22:57 UTC, aurelticot commented on docs/demos.md
> +which demonstrates use cases, features and capabilities of the Verida Vault (eg single sign-on, send a credential, request some data) </summary>
No, I meant it was ok before: "sign on"

2022-08-30 23:06 UTC, aurelticot requested changes

2022-08-30 23:06 UTC, aurelticot commented on docs/demos.md
> +which demonstrates use cases, features and capabilities of the Verida Vault (eg singing in , send a credential, request some data) </summary>
"sing in"

2022-08-31 06:45 UTC, aurelticot requested changes

2022-08-31 06:45 UTC, aurelticot commented on docs/extensions/vue-starter-kit.md
> +This component is used to display a logged-in user profile details such as `name`, `did` and `avatar`. If the user is not logged-in it will supply a sign-in link and generate the single sign-on logge
Just copy and replace this sentence so we don't waste more time:

"This component is used to display a logged in user's profile details such as `name`, `did` and `avatar`. If the user is not logged in, it will supply a login link and generate the single sign-on login form in the same way the `vda-login` component does."

2022-08-31 10:10 UTC, cmcWebCode40 commented on docs/extensions/vue-starter-kit.md
> +This component is used to display a logged-in user profile details such as `name`, `did` and `avatar`. If the user is not logged-in it will supply a sign-in link and generate the single sign-on logge
Done ✅

2022-09-01 01:15 UTC, aurelticot approved these changes
Ok

2022-09-01 04:59 UTC, merged