Feature/129 add walletconnect veridaconnect tutorial
verida/documentation pull request #131
Opened 2022-10-28 15:21 UTC by cmcWebCode40

## Completed Tasks

- [ ] Take the "Sign Personal" example from https://example.walletconnect.org/

- [ ]  Modify to get the Profile Name from the Verida Profile

- [ ]  Sign a message saying "My name is " using WalletConnect

- [ ]  Updated documentation for wallet connect + verida connect tutorial

NB: From the (Sign Personal Message (personal_sign) ) example  I dont think the `convertUTF8toHex()` was used  because the i `message` still display in the vault as UTF8 format .

## Demo

https://www.loom.com/share/da29f180106046ad9bfe1a2654e6dc44

2022-10-31 02:17 UTC, nick-verida requested changes
When I press the "Sign Personal Message" button I get this:

![image](https://user-images.githubusercontent.com/87622993/198917322-92816942-bd7c-4400-8380-eb44caed58b0.png)

We need to:

* Make sure we handle this error
* Need to fix whatever the problem is
* If the person has previously logged on (using the normal wallet connect login) I don't think this will handle the fact we don't have a WC session for them either.

2022-10-31 02:17 UTC, nick-verida commented on docs/tutorial/SSO.mdx
> +		);
This is wrong

![image](https://user-images.githubusercontent.com/87622993/198916058-744f01d1-76bc-4958-a989-2914f863b2de.png)

2022-10-31 02:17 UTC, nick-verida commented on docs/single-sign-on-sdk/how-to-use-the-sso-sdk.md
> +const DEFAULT_CHAIN_ID = "eip155:1"
There's no way to change the chain_id after it is used so call this CHAIN_ID (instead of DEFAULT_CHAIN_ID)

2022-10-31 02:17 UTC, nick-verida commented on docs/tutorial/walletconnect_verida.mdx
> +        const DEFAULT_CHAIN_ID = 'eip155:1';
CHAIN_ID (not DEFAULT_CHAIN_ID)

2022-10-31 02:17 UTC, nick-verida commented on docs/tutorial/walletconnect_verida.mdx
> +					is:
Need a space after the link 
![image](https://user-images.githubusercontent.com/87622993/198917146-653b4e9e-2160-423a-9ae4-7e343174df7e.png)

2022-10-31 14:54 UTC, cmcWebCode40 commented on docs/tutorial/SSO.mdx
> +		);
I couldn't reproduce this issue ,

tested severally and the code editor works as expected

2022-10-31 14:55 UTC, cmcWebCode40 commented on docs/single-sign-on-sdk/how-to-use-the-sso-sdk.md
> +const DEFAULT_CHAIN_ID = "eip155:1"
fixed

2022-10-31 14:55 UTC, cmcWebCode40 commented on docs/tutorial/walletconnect_verida.mdx
> +					is:
fixed

2022-10-31 15:02 UTC, cmcWebCode40 commented
@nick-verida ,

The above error for "session currently disconnected"  will occur if these two events

- When a developer tries to test the code editor using an older version of our vault app
- When a developer already  disconnects the connect wc Dapp from our vault 

I was able to add a caution note to show some steps on how to resolve the issue as seen in this screenshot
<img width="700" alt="Screenshot 2022-10-31 at 15 53 05" src="https://user-images.githubusercontent.com/54280620/199039327-06a277e0-93da-4e5c-8111-0ada439aaa7a.png">

Here is also a readable logged error displayed in the editor preview that will display 
<img width="834" alt="Screenshot 2022-10-31 at 15 41 31" src="https://user-images.githubusercontent.com/54280620/199039600-261ff7a2-dd3f-441b-9885-fb3163615bdd.png">

2022-11-01 00:22 UTC, aurelticot commented on docs/tutorial/SSO.mdx
>  ---
@nick-verida, how about we keep this tutorial page focus on Verida Connect alone, knowing there is a dedicated tutorial page Verida Connect + WalletConnect?

It may look like WalletConnect is required to connect with Verida

2022-11-01 00:22 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +The code below shows how to login to the Verida network using the verida connect which uses wallet connect an optional configuration to automatically establish a wallet connection upon sign in .
A few typos, following names should always be written this way: "Verida Network", "Verida Connect" and "ValletConnect"

2022-11-01 00:22 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +You may get an error that display : "Session is disconnected"  this means you're currently logged in without a Wallet connect session.
Typo: "Wallet connect" to "WalletConnect"

2022-11-01 00:22 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> + -  Login again to establish a wc session
Use: "WalletConnect session" instead of "wc session"

2022-11-01 00:22 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +    getProfile = async function (context) {
@nick-verida, conscious of the amount of code in this page, how about we sign the personal message with the DID instead of the Name, so that we can remove all the code related to the profile?
Idea being to focus on WalletConnect.

2022-11-01 00:22 UTC, aurelticot commented on docs/single-sign-on-sdk/how-to-use-the-sso-sdk.md
>  ```jsx
Having the WalletConnect example may looks like it is necessary to have use it.

How about we keep this code as it was, and add a new code sample afterwards showing how WalletConnect can be added into. We also need to add a paragraph explaining it is optional. That the Vault supports WalletConnect for its crypto wallet with this unified connection experience for the user.

@nick-verida

2022-11-01 00:22 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +The code below shows how to login to the Verida network using the verida connect which uses wallet connect an optional configuration to automatically establish a wallet connection upon sign in .
I feel this sentence is unclear.
My suggestion:
"The code below shows how to connect with both the Verida Network and WalletConnect" providing a unified connection experience for the user."

2022-11-01 00:22 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +The code below shows how to login to the Verida network using the verida connect which uses wallet connect an optional configuration to automatically establish a wallet connection upon sign in .
@nick-verida

2022-11-01 00:26 UTC, nick-verida commented on docs/tutorial/walletconnect_verida.mdx
> +    getProfile = async function (context) {
@aurelticot yes good point.

@cmcWebCode40 Can you please update to just sign with the DID? That make this much less overwhelming.

2022-11-01 03:03 UTC, nick-verida requested changes

2022-11-01 03:03 UTC, nick-verida commented on docs/tutorial/walletconnect_verida.mdx
> +				{errorMessage}
When the "Sign Personal Message" button is pressed please show a message: "Please check your vault to sign this message".

In the dialog that shows up the address is showing as **null**

![image](https://user-images.githubusercontent.com/87622993/199149246-198e7f3a-44cc-4494-b66b-eaa5f8726872.png)

2022-11-01 03:03 UTC, nick-verida commented on docs/tutorial/walletconnect_verida.mdx
> + - You have to ensure vault app is updated to the latest version
"Please ensure the Verida Vault is updated to the latest version"

2022-11-01 03:12 UTC, aurelticot commented on docs/tutorial/SSO.mdx
>  ---
Ah, because the session is kept from one page to another and if the user clicks "login" again, it will be auto-connected.

We don't have a way to clear the previous session and initiate a new connection?

2022-11-01 04:19 UTC, cmcWebCode40 commented on docs/tutorial/SSO.mdx
>  ---
> We don't have a way to clear the previous session and initiate a new connection?
yes, we don't have a way to clear the previous session because a user only needs to log in once and uses our verida connect context to test other tutorials.

2022-11-01 06:16 UTC, cmcWebCode40 commented on docs/tutorial/walletconnect_verida.mdx
> +The code below shows how to login to the Verida network using the verida connect which uses wallet connect an optional configuration to automatically establish a wallet connection upon sign in .
Fixed typos

2022-11-01 06:16 UTC, cmcWebCode40 commented on docs/tutorial/walletconnect_verida.mdx
> +You may get an error that display : "Session is disconnected"  this means you're currently logged in without a Wallet connect session.
fixed

2022-11-01 06:16 UTC, cmcWebCode40 commented on docs/tutorial/walletconnect_verida.mdx
> + -  Login again to establish a wc session
fixed

2022-11-01 06:16 UTC, cmcWebCode40 commented on docs/tutorial/walletconnect_verida.mdx
> +				{errorMessage}
fixed this wallet address issue

2022-11-01 06:16 UTC, cmcWebCode40 commented on docs/tutorial/walletconnect_verida.mdx
> +				 Please click the on the logout button, then  update version of the version of vault app and login again to establish a wc session
fixed

2022-11-01 06:16 UTC, cmcWebCode40 commented on docs/single-sign-on-sdk/how-to-use-the-sso-sdk.md
> +  },
added comment

2022-11-02 04:53 UTC, aurelticot requested changes
Some changes to complete

2022-11-02 04:53 UTC, aurelticot commented on docs/single-sign-on-sdk/how-to-use-the-sso-sdk.md
> +const DEFAULT_CHAIN_ID = "eip155:1"
This is still `DEFAULT_CHAIN_ID` with the latest commit

2022-11-02 04:53 UTC, aurelticot commented on docs/single-sign-on-sdk/how-to-use-the-sso-sdk.md
> +  },
I don't see the comment, where is it?

2022-11-02 04:53 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +	login = async function  () {
The indentation within the whole `login` method is not correct

2022-11-02 04:53 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +			    // An optional WalletConnect object
On this tutorial page focus on WalletConnect, we don't want this comment saying it's optional as it is actually required to enable the Verida Connect + WalletConnect connection.

You can replace it by a comment saying:
```jsx
// Pass the WalletConnect details required for the connection
```

2022-11-02 04:53 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +	signInPersonalMessage = async function(){
The indentation within the whole `signPersonalMessage` method is not correct

2022-11-02 04:53 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +    initWalletConnect = async function () {
The indentation within the whole `initWalletConnect` method is not correct

2022-11-02 04:53 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +				Wallet Connect : ${error.message}
"WalletConnect" instead of "Wallet Connect"

2022-11-02 04:53 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +				login again to establish a wc session
"...WalletConnect session" instead of "wc session"

2022-11-02 04:53 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +	if (veridaContext) {
Can you rework the indentation in this `if` statement as well?

2022-11-07 23:42 UTC, nick-verida requested changes
One final change

2022-11-07 23:42 UTC, nick-verida commented on docs/tutorial/walletconnect_verida.mdx
> +              walletConnector &&
Functionally this is correct, but we don't want separate logout/disconnect WC buttons. 

The "Logout" button should call both (in the same way that "Login" handles both)

2022-11-08 04:59 UTC, cmcWebCode40 commented on docs/tutorial/walletconnect_verida.mdx
> +              walletConnector &&
@nick-verida , i have refactored the logout function to handle disconnect wallet connect session

2022-11-27 22:38 UTC, nick-verida commented
@cmcWebCode40 when I press "Sign Personal Message" I get the following in the browser console:

```
Object { error: Error }
vendors-node_modules_mdx-js_react_dist_esm_js-node_modules_verida_account-web-vault_dist_inde-c2b24c.js line 120952 > Function:136:15
Object { error: Error }
​
error: Error: Failed or Rejected Request
​​
columnNumber: 31
​​
fileName: "http://localhost:3000/vendors-node_modules_mdx-js_react_dist…js-node_modules_verida_account-web-vault_dist_inde-c2b24c.js"
​​
lineNumber: 52358
​​
message: "Failed or Rejected Request"
​​
stack: "trigger/<@http://localhost:3000/vendors-node_modules_mdx-js_react_dist_esm_js-node_modules_verida_account-web-vault_dist_inde-c2b24c.js:52358:31\ntrigger@http://localhost:3000/vendors-node_modules_mdx-js_react_dist_esm_js-node_modules_verida_account-web-vault_dist_inde-c2b24c.js:52356:23\n_handleIncomingMessages@http://localhost:3000/vendors-node_modules_mdx-js_react_dist_esm_js-node_modules_verida_account-web-vault_dist_inde-c2b24c.js:53095:32\nasync*_initTransport/<@http://localhost:3000/vendors-node_modules_mdx-js_react_dist_esm_js-node_modules_verida_account-web-vault_dist_inde-c2b24c.js:53191:63\n_socketReceive/<@http://localhost:3000/vendors-node_modules_mdx-js_react_dist_esm_js-node_modules_verida_account-web-vault_dist_inde-c2b24c.js:55111:47\n_socketReceive@http://localhost:3000/vendors-node_modules_mdx-js_react_dist_esm_js-node_modules_verida_account-web-vault_dist_inde-c2b24c.js:55111:24\n_socketCreate/this._nextSocket.onmessage@http://localhost:3000/vendors-node_modules_mdx-js_react_dist_esm_js-node_modules_verida_account-web-vault_dist_inde-c2b24c.js:55060:54\n"
​​
<prototype>: Error.prototype { stack: "", … }
​
<prototype>: Object { … }
vendors-node_modules_mdx-js_react_dist_esm_js-node_modules_verida_account-web-vault_dist_inde-c2b24c.js line 120952 > Function:136:15
```

Can we please:
* Fix this
* Make sure the web page shows an error status if there is an error

2022-11-28 04:57 UTC, cmcWebCode40 commented
@nick-verida , 
Please can you provide steps on how I can replicate this error?
I have tried to test it but couldn't replicate the error.

2022-11-30 11:29 UTC, andy-verida requested changes
As a result of my test for fixing the WC stale state issue https://github.com/verida/vault-mobile/issues/761
I think this demo is missing a key ability to reconnect to WC when refreshing the document page. Like I need to log out and log in again to use WC.

2022-11-30 20:58 UTC, cmcWebCode40 commented
@andy-verida , 

can you do a screen recording so I can confirm this issue?

because from the code implementation when the page is refreshed it handles auto-login if there's an existing verida / WC session .

2022-12-01 04:32 UTC, andy-verida commented
> @andy-verida ,
> 
> can you do a screen recording so I can confirm this issue?
> 
> because from the code implementation when the page is refreshed it handles auto-login if there's an existing verida / WC session .

@cmcWebCode40 I've just tested again, and don't see that issue anymore.

2022-12-07 13:43 UTC, cmcWebCode40 commented
@Andy concerning this issue that you have fixed [vault-mobile/issues/761](https://github.com/verida/vault-mobile/issues/761)
 I have tested the WC + verida connect in our docs and it works  now but I found out that the dapp screen in the vault that shows a list of connected dapps is blank have attempted this twice and the screen still remains blank.

cc @nick-verida 
 
 
![IMG_0409](https://user-images.githubusercontent.com/54280620/206194350-f627f953-3130-44ff-9f3c-53c9bc58bf74.PNG)

2022-12-07 14:54 UTC, andy-verida commented
@cmcWebCode40 That issue is weird, I will check again it.

2022-12-08 06:47 UTC, aurelticot commented
When I checked Andy's PR fixing WalletConnect I haven't tried on the documentation tutorial, but with the WalletConnect example (https://example.walletconnect.org/) and on the DeFi demo app, both showed in the list of connected dApps

2022-12-12 09:58 UTC, andy-verida commented
@cmcWebCode40 I couldn't reproduce the issue of your report here https://github.com/verida/documentation/pull/131#issuecomment-1340987679

I guess having something account state-related specific. Could you demo it to me?

2022-12-19 19:41 UTC, cmcWebCode40 commented
> @cmcWebCode40 That issue is weird, I will check again it.

@Andy I checked this problem once more in "Vault internal build 0.3.36," and it has been fixed.
thanks

2022-12-19 22:49 UTC, andy-verida commented
> 

@cmcWebCode40 thanks.

2022-12-28 01:23 UTC, aurelticot commented
@cmcWebCode40 can you have a look at the previous review comment that haven't been resolved and fix them if still relevant?
Thanks

2022-12-28 11:50 UTC, cmcWebCode40 commented
@aurelticot , i just fixed a minor comment from this change request

2022-12-29 00:25 UTC, aurelticot requested changes

2022-12-29 00:25 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +description: Verida Developer Tutorial - verida connect and Wallet connect
Typos in description:
"... - Verida Connect and WalletConnect"

2022-12-29 00:25 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +keywords: [Verida, Web3, Developers, Tutorial, Verida Connect, Wallet connect]
Typo: "WalletConnect"

2022-12-29 00:25 UTC, aurelticot commented on docs/tutorial/SSO.mdx
> +description: Verida Developer Tutorial - verida connect and Wallet connect
Typo: "... Verida Connect and WalletConnect"

2022-12-29 00:25 UTC, aurelticot commented on docs/tutorial/SSO.mdx
> +keywords: [Verida, Web3, Developers, Tutorial, Verida Connect, Wallet connect]
Typo: "... WalletConnect"

2022-12-29 00:25 UTC, aurelticot commented on docs/tutorial/SSO.mdx
> +	const [walletAddress, setWalletAddress] = useState(null);
Typo in the "Try it out" paragraph above
"The code below show how to login to the Verida Network"

2022-12-29 00:25 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +    // see link to learn more on how to initialize wallet connect
Typo: "... how to initialize WalletConnect"

2022-12-29 00:25 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +        {isLoading ? 'Verida connect in progress please wait....' :
Could you reword to "Connection to Verida in progress ..."

2022-12-29 00:25 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +				Please click the on the logout button and
Typo: "Please click the logout button and login button ..."

2022-12-29 00:25 UTC, aurelticot commented on docs/tutorial/walletconnect_verida.mdx
> +The code below shows how to login to the Verida network using the verida connect which uses wallet connect an optional configuration to automatically establish a wallet connection upon sign in .
@cmcWebCode40 there were still several typos in this page and others. I added a comment for all I found.

2023-01-16 00:34 UTC, nick-verida commented
I think the Vault fixes for this to work are now published

2023-01-16 00:34 UTC, merged