Add draft documentation about Personal Data Bridge
verida/documentation pull request #132
Opened 2022-12-07 08:59 UTC by tahpot

2022-12-12 08:45 UTC, aurelticot commented on docs/extensions/personal-data-bridge.md
> +`VDAVerificationContract.sol` provies an easier way to manage this from your smart contracts.
Typo "... provides an easier ..."

2022-12-12 08:45 UTC, aurelticot commented on docs/extensions/personal-data-bridge.md
> +const signedRequest = await keyring.sign(requestParamsWithNonce)
Should be `customerKeyring`

2022-12-12 08:45 UTC, aurelticot commented on docs/extensions/personal-data-bridge.md
> +await contract.submitCreditScore(getAddressFromDid(did), requestParams, signedRequest, customerContextProof)
Which `did` it is?
I guess `customerDid`?

2023-01-18 07:50 UTC, tahpot commented on docs/extensions/personal-data-bridge.md
> +await contract.submitCreditScore(getAddressFromDid(did), requestParams, signedRequest, customerContextProof)
Yep, fixed.

2023-01-18 07:50 UTC, tahpot commented on docs/extensions/personal-data-bridge.md
> +const signedRequest = await keyring.sign(requestParamsWithNonce)
Fixed.

2023-01-18 07:51 UTC, tahpot commented on docs/extensions/personal-data-bridge.md
> +`VDAVerificationContract.sol` provies an easier way to manage this from your smart contracts.
Fixed

2023-01-19 02:25 UTC, aurelticot requested changes
In addition to the inline comments, there were a bunch of comments I made in a [previous PR](https://github.com/verida/documentation/pull/131/files) that were not taken into account. Any chance we can fix the typos and other suggestions?

2023-01-19 02:42 UTC, nick-verida commented on docs/concepts/data-storage.md
> +## How is data syncronized between applications?
No this is a typo

2023-01-19 02:43 UTC, nick-verida commented on docs/concepts/data-storage.md
> +This ensures tht if one of the storage nodes becomes unavailable, there are two other nodes that still have copies of the data and the user can continue uninterupted.
uninterupted -> uninterrupted

2023-01-19 02:44 UTC, nick-verida commented on docs/concepts/accounts-and-identity.md
> +If you need help spinning up your own storage node, please contact us.
I think there is a contact form, linking to https://discord.verida.io would also work

2023-01-19 02:48 UTC, nick-verida commented
This change has a bunch of broken links. The GitHub action shows errors, and there are a number of warnings

Run `yarn build` (**not** just `yarn start`)  to check them:

[ERROR] Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /docs/client-sdk/how-it-works:
   -> linking to ../network/storage-node.md (resolved as: /docs/network/storage-node.md)

- On source page path = /docs/concepts/accounts-and-identity:
   -> linking to Authentication (resolved as: /docs/concepts/Authentication)

- On source page path = /docs/concepts/network-architecture:
   -> linking to ../network/storage-node.md (resolved as: /docs/network/storage-node.md)

- On source page path = /docs/intro:
   -> linking to /docs/demos

- On source page path = /docs/single-sign-on-sdk:
   -> linking to the-sso-authentication-server.md (resolved as: /docs/the-sso-authentication-server.md)

- On source page path = /docs/single-sign-on-sdk/sso-authentication-server:
   -> linking to ./single-sign-on-sdk/getting-started#configuration (resolved as: /docs/single-sign-on-sdk/single-sign-on-sdk/getting-started)


[WARNING] Docs markdown link couldn't be resolved: (../network/storage-node.md) in /Users/nlothian/dev/verida/documentation/docs/concepts/network-architecture.md for version current
[WARNING] Docs markdown link couldn't be resolved: (the-sso-authentication-server.md) in /Users/nlothian/dev/verida/documentation/docs/single-sign-on-sdk/single-sign-on-sdk.md for version current
[WARNING] Docs markdown link couldn't be resolved: (the-sso-authentication-server.md) in /Users/nlothian/dev/verida/documentation/docs/single-sign-on-sdk/single-sign-on-sdk.md for version current
[WARNING] Docs markdown link couldn't be resolved: (../network/storage-node.md) in /Users/nlothian/dev/verida/documentation/docs/concepts/network-architecture.md for version current
[WARNING] Docs markdown link couldn't be resolved: (../network/storage-node.md) in /Users/nlothian/dev/verida/documentation/docs/client-sdk/how-it-works.md for version current
[WARNING] Docs markdown link couldn't be resolved: (../network/storage-node.md) in /Users/nlothian/dev/verida/documentation/docs/client-sdk/how-it-works.md for version current

2023-01-19 02:50 UTC, nick-verida requested changes
There are lots of typos that need fixing (maybe install https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker - I assume it works for Markdown)

Also a number of broken links which stop it from building. 

Run `yarn build` to check and fix.

2023-01-19 03:17 UTC, tahpot commented on docs/concepts/data-storage.md
> +## How do Verida Accounts authenticate with Storage Modes?
Fixed

2023-01-19 03:18 UTC, tahpot commented on docs/concepts/data-storage.md
> +## How is data syncronized between applications?
Fixed

2023-01-19 03:18 UTC, tahpot commented on docs/concepts/data-storage.md
> +Verida solve all these data storage problems in a way that is capable of scaling to billions of users and enable decentralized apps to be built that can compete directly with Web2 applications.
Fixed. Updated wording.

2023-01-19 03:18 UTC, tahpot commented on docs/concepts/data-storage.md
> +Users grant access to authentications to access and decrypt portions of their data stored on nodes across the network.
Fixed, should be "grant access to applications"

2023-01-19 03:20 UTC, tahpot commented on docs/concepts/data-storage.md
> +User data is encrypted using private keys stored on the end user's device. For example, if a user logs into an application in their web browser, an encryption key exists in the browser to encrypt and
Good point. Have updated the wording, is that better?

2023-01-19 03:21 UTC, tahpot commented on docs/concepts/data-storage.md
> +Verida Accounts have multiple containers for storing data (called [application contexts](./application-contexts)). Each of these `application contexts` are completely independent. They have independe
The architecture allows them to be different, but by default the Verida Wallet uses the same ones for every context.

2023-01-19 03:22 UTC, tahpot commented on docs/concepts/data-storage.md
> +We have written an overview of the types of Web3 data that provide helpful background information and context for where the Verida network offers the biggest value as a data storage solution.
Agreed. Updated.

2023-01-19 03:23 UTC, tahpot commented on docs/concepts/accounts-and-identity.md
> +DID's are more than just an address. The specification supports creating DID Documents that provide enhanced discovery of services being operated for that DID (ie: storage, messaging) and public keys
Fixe

2023-01-19 03:24 UTC, tahpot commented on docs/concepts/accounts-and-identity.md
> +If you need help spinning up your own storage node, please contact us.
Added both.

2023-01-19 04:17 UTC, aurelticot commented on docs/concepts/data-storage.md
> +## How is data syncronized between applications?
You have to check the "h" key of your keyboard @tahpot :-)

2023-01-19 04:22 UTC, aurelticot commented on docs/concepts/data-storage.md
> +Verida Accounts have multiple containers for storing data (called [application contexts](./application-contexts)). Each of these `application contexts` are completely independent. They have independe
Applications could use other Storage nodes than the ones defined by the user?

2023-01-19 04:22 UTC, aurelticot commented on docs/concepts/data-storage.md
> +User data is encrypted using private keys stored on the end user's device. For example, if a user logs into an application in their web browser, an encryption key exists in the browser to encrypt and
Yep

2023-01-19 04:27 UTC, aurelticot approved these changes

2023-01-19 04:51 UTC, aurelticot requested changes

2023-01-19 04:51 UTC, aurelticot commented on docs/single-sign-on-sdk/single-sign-on-sdk.md
> +A user downloads the Verida Wallet onto their mobile device which generates a private key on a supported blockchain. This private key is used to generated a Decentralized Identity (DID). The user the
Typo "...is used to generate a Decentralized..."

2023-01-19 23:32 UTC, nick-verida commented on docs/single-sign-on-sdk/single-sign-on-sdk.md
> +A user downloads the Verida Wallet onto their mobile device which generates a private key on a supported blockchain. This private key is used to generated a Decentralized Identity (DID). The user the
I've pushed a change to fix this

2023-01-19 23:32 UTC, nick-verida commented
Looks good here. 

I'm merging to `develop`

2023-01-19 23:34 UTC, merged