add doc for zkPass
verida/documentation pull request #234
Opened 2024-05-07 05:45 UTC by icetrust0212

2024-05-08 03:34 UTC, tahpot requested changes
It should be `zkPass` not `ZkPass`.

`redirects` should be `redirect`

2024-05-08 03:34 UTC, tahpot commented on docs/extensions/credentials/zkpass.md
> +You need to provide `veridaDid` where generated credential will go to in the url. For example, the url can be like [this](https://proof.verida.network/add-credential?veridaDid=did:vda:mainnet:0x378E2
Show the actual URLs

2024-05-08 03:34 UTC, tahpot commented on docs/extensions/credentials/zkpass.md
> +It will redirects you to page where you select schemas.
Make it clear users can request a schema in the URL.

List all the currently supported schemas.

2024-05-08 03:34 UTC, tahpot commented on docs/extensions/credentials/zkpass.md
> +export type ZkPassResult = {
Does this code section need a heading and a description? I'm unclear why it's here.

2024-05-08 03:34 UTC, tahpot commented on docs/extensions/credentials/zkpass.md
> +---
I think this documentation should have a slightly different structure:

1. Requesting a zkPass credential (code example requesting a credential from the user's inbox)
2. Issuing a zkPass credential (code example, explain schemas, list all the schemas; make it clear this is only needed if the user doesn't have the credential)
3. Verifying a credential (code example to verify from an inbox response using the zkPass SDK, also explain and link to the proof connector verify page)

2024-05-14 02:26 UTC, icetrust0212 commented on docs/extensions/credentials/zkpass.md
> +It will redirects you to page where you select schemas.
Done

2024-05-14 02:26 UTC, icetrust0212 commented on docs/extensions/credentials/zkpass.md
> +You need to provide `veridaDid` where generated credential will go to in the url. For example, the url can be like [this](https://proof.verida.network/add-credential?veridaDid=did:vda:mainnet:0x378E2
Done

2024-05-14 02:39 UTC, icetrust0212 commented on docs/extensions/credentials/zkpass.md
> +export type ZkPassResult = {
Done

2024-05-14 04:20 UTC, icetrust0212 commented on docs/extensions/credentials/zkpass.md
> +---
Done

2024-06-13 00:49 UTC, tahpot approved these changes
LFG

2024-06-13 00:50 UTC, merged